// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUETSy0XK5qQe3eHZF4X890a9Es5uBg2g',
    appId: '1:828732015536:web:b40b22aedc54fa0ac88c75',
    messagingSenderId: '828732015536',
    projectId: 'smart-plant-health-monitor',
    authDomain: 'smart-plant-health-monitor.firebaseapp.com',
    storageBucket: 'smart-plant-health-monitor.firebasestorage.app',
    measurementId: 'G-9FWSV02EP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjoEol7SYWNGvCv2sbkJztm6YSo-1gNs',
    appId: '1:828732015536:android:cea2c37d5f1c12a3c88c75',
    messagingSenderId: '828732015536',
    projectId: 'smart-plant-health-monitor',
    storageBucket: 'smart-plant-health-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRBt6mCilsNhiKfl_OqoNavrhKBRk4i4',
    appId: '1:828732015536:ios:405668ee3e9380f9c88c75',
    messagingSenderId: '828732015536',
    projectId: 'smart-plant-health-monitor',
    storageBucket: 'smart-plant-health-monitor.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRBt6mCilsNhiKfl_OqoNavrhKBRk4i4',
    appId: '1:828732015536:ios:405668ee3e9380f9c88c75',
    messagingSenderId: '828732015536',
    projectId: 'smart-plant-health-monitor',
    storageBucket: 'smart-plant-health-monitor.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUETSy0XK5qQe3eHZF4X890a9Es5uBg2g',
    appId: '1:828732015536:web:d79ca0691657e9c0c88c75',
    messagingSenderId: '828732015536',
    projectId: 'smart-plant-health-monitor',
    authDomain: 'smart-plant-health-monitor.firebaseapp.com',
    storageBucket: 'smart-plant-health-monitor.firebasestorage.app',
    measurementId: 'G-80W3W6CSQW',
  );
}
